name: PHPUnit Tests
on:
  push:
  pull_request:

jobs:
  test-php:
    name: ${{ matrix.php_versions }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php_versions: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

