name: SonarCloud
on:
  push:
  pull_request:

jobs:
  sonarcloud:
    name: 'PHPUnit and Jest Tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug
